### ISSUE TITLE
Packaging nwjs apps not working in Windows: [ERR_FS_CP_DIR_TO_NON_DIR] error

### ISSUE THREAD

**Issue by ez-yahya** [nwutils/nw-builder#811]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

Packaging nwjs applications in Windows with nw-builder v4.1.0 throws the following error:

SystemError [ERR_FS_CP_DIR_TO_NON_DIR]: Cannot overwrite directory with non-directory

The error is thrown from https://github.com/nwutils/nw-builder/blob/main/src/bld/package.js#L40

The srcDir I passed is: ./src/nwapp/* , if I remove the globing '*', the above cp command is fixed but then it fails to resolve the package.json.

### Expected/Proposed Behaviour

Packaging nwjs apps in Windows

### Additional Info

- Package version: 4.1.0
- Operating System: Windows
- Node version: 18.13.0

**Comment by tharatau** [comment]
Are you packaging for MacOS platform on Windows?

**Comment by tharatau** [comment]
Same error in v4.1.0-beta.3?

**Comment by williamwang96** [comment]
I think @ez-yahya 's error is probably caused by #814.

**Comment by tharatau** [comment]
The patch for this error is here:
https://github.com/nwutils/nw-builder/issues/819#issuecomment-1475274605
I'll make a release soon.

**Comment by tharatau** [comment]
If you disable glob, it should work now. Tracking that in #836

**Comment by ez-yahya** [comment]
Thank you for improving it @tharatau! I tried disabling glob, it works on Mac but fails on Windows with a different error now (it doesn't resolve the files correctly). Should we disable globbing here as well https://github.com/nwutils/nw-builder/blob/main/src/util/files.js#L15 ?

**Comment by sysrage** [comment]
> Should we disable globbing here as well

The `getFiles()` function you linked is never called if globbing is disabled: https://github.com/nwutils/nw-builder/blob/68d35934a7a4fef0c5156c82ec6b9071a8a39bc3/src/nwbuild.js#L101

Windows builds work great for me with globbing disabled. You'll need to open a new issue with the new error you're getting.

**Comment by ez-yahya** [comment]
Ok, I'm testing it from the latest 4.2.0 release, which does not have the changes that you linked https://github.com/nwutils/nw-builder/blob/v4.2.0/src/nwbuild.js#L101

**Comment by tharatau** [comment]
Latest is 4.2.1

**Comment by ez-yahya** [comment]
Verified on 4.2.1, works fine, thanks!
